name: expense_repo
description: The repo that handle expenses
publish_to : 'none'
version: 0.0.1

environment:
  sdk: '^3.7.2'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2
  #rxdart: ^0.27.7


dev dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
