// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEtGa3WENp6voUCYyS0YyeGmdOFIqPfEo',
    appId: '1:989257343700:web:34211f65f71c5ca3865141',
    messagingSenderId: '989257343700',
    projectId: 'expense-tracker-50dee',
    authDomain: 'expense-tracker-50dee.firebaseapp.com',
    storageBucket: 'expense-tracker-50dee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxRmH6uaf7NnPW_DD0Pv1y-MXAluxNdJw',
    appId: '1:989257343700:android:b8027d4ec2d7ff31865141',
    messagingSenderId: '989257343700',
    projectId: 'expense-tracker-50dee',
    storageBucket: 'expense-tracker-50dee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3AMheBa-Rt4UZTikfSgQGTAvtqv_cDo8',
    appId: '1:989257343700:ios:7a2c437b9359b48b865141',
    messagingSenderId: '989257343700',
    projectId: 'expense-tracker-50dee',
    storageBucket: 'expense-tracker-50dee.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3AMheBa-Rt4UZTikfSgQGTAvtqv_cDo8',
    appId: '1:989257343700:ios:7a2c437b9359b48b865141',
    messagingSenderId: '989257343700',
    projectId: 'expense-tracker-50dee',
    storageBucket: 'expense-tracker-50dee.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEtGa3WENp6voUCYyS0YyeGmdOFIqPfEo',
    appId: '1:989257343700:web:6a657a37013fa663865141',
    messagingSenderId: '989257343700',
    projectId: 'expense-tracker-50dee',
    authDomain: 'expense-tracker-50dee.firebaseapp.com',
    storageBucket: 'expense-tracker-50dee.firebasestorage.app',
  );
}
